name 'thbe-ssmtp'
version '0.2.6'

author 'Thomas Bendler <project@bendler-net.de>'
license 'GPLv3'
project_page 'https://github.com/thbe/puppet-ssmtp.git'
source 'https://github.com/thbe/puppet-ssmtp.git'
summary 'sSMTP management module'
description 'sSMTP management module'
dependency 'puppetlabs/stdlib', '>=2.2.0'
